# This workflow runs static analysis on RepoBee

name: update-readme

on:
  push:
    branches: [ source ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Update README
      run: |
        python update.py
    - name: Commit files on master
      run: |
        git config --local user.email "slarse@slar.se"
        git config --local user.name "Simon Larsén"

        git symbolic-ref HEAD refs/heads/master
        git add --force .
        git commit -am "Update README"

        # if there were no changes, the commit will fail, but we don't actually
        # care about that and so exit 0 anyway
        exit 0
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: "master"
